import type { Lang } from '../../../shared/api'

// Strings of the /verify page (command 17). Kept apart from i18n/*.ts while those files have another window's
// uncommitted work. Arabic and English are reviewed; the eight others are machine-translated like the rest of the UI.
// The package's case texts stay in Arabic, verbatim, in every language.
export type VerifyStrings = {
  title: string
  intro: string
  demo: string
  honest: string
  modelMock: string
  packageArabic: string
  caseN: string
  packageCase: string
  question: string
  expected: string
  appDid: string
  type: Record<'answer' | 'abstain' | 'referral' | 'error', string>
  disputed: string
  quotes: string
  noQuotes: string
  result: string
  pass: string
  fail: string
  manual: string
  manualNote: string
  checks: string
  tryNow: string
  tryHint: string
  tally: string
  compareTitle: string
  compareIntro: string
  compareNone: string
  metric: string
  run: string
  general: string
  ours: string
  cites: string
  refsInSources: string
  misattributed: string
  hadithRefs: string
  allVerified: string
  reportsTitle: string
  judgesLink: string
  toolTitle: string
  toolIntro: string
  toolModelUnknown: string
  toolSetup: string
  sameModel: string
  otherTool: string
}

const ar: VerifyStrings = {
  title: 'تحقّق بنفسك',
  intro: 'حالات الاختبار الرسمية من الحزمة العلمية للتحدي، وإجابة التطبيق على كل منها، ونتيجة القياس الحي.',
  demo: 'بيانات تجريبية: هذه النتائج من تشغيل بوضع المحاكاة لتجربة الصفحة، وتُستبدل بالقياس الحي.',
  honest: 'تاريخ القياس: {date} · النموذج: {model} · الحكم على الحالات اليدوية من الفريق.',
  modelMock: 'وضع المحاكاة، بلا نموذج لغوي',
  packageArabic: '',
  caseN: 'الحالة {n}',
  packageCase: 'حالة الحزمة',
  question: 'السؤال المحدد',
  expected: 'السلوك المتوقع بنص الحزمة',
  appDid: 'ما فعله التطبيق',
  type: { answer: 'إجابة بالنص ومرجعه', abstain: 'اعتذار: لا نص يطابق', referral: 'إحالة إلى جهة الفتوى', error: 'خطأ في التشغيل' },
  disputed: 'صرّح بأن في المسألة أكثر من قول',
  quotes: 'الشواهد',
  noQuotes: 'بلا شواهد',
  result: 'النتيجة',
  pass: 'ناجح',
  fail: 'راسب',
  manual: 'يدوي',
  manualNote: 'يحكم عليه الفريق: {text}',
  checks: 'الفحوص الآلية',
  tryNow: 'جرّبها الآن',
  tryHint: 'يضع السؤال في خانة المحادثة، ولا يُرسل إلا بضغطتك.',
  tally: '{pass} ناجح · {fail} راسب · {manual} يدوي، من {n}',
  compareTitle: 'المقارنة بالنموذج العام',
  compareIntro: 'النموذج نفسه يجيب بلا مقاطع ويُطلب منه ذكر مصدره، على {n} سؤالًا من أسئلة الاختبار، والقياس مكرر ثلاث مرات.',
  compareNone: 'لم يُقس بعد. يُملأ هذا الجدول من تقرير المقارنة بعد القياس الحي.',
  metric: 'المقياس',
  run: 'المرة {n}',
  general: 'النموذج العام',
  ours: 'مسلم',
  cites: 'ذكر مرجعًا',
  refsInSources: 'مراجع قرآنية موجودة في المصادر',
  misattributed: 'نص منسوب لآية لا يطابق نصها',
  hadithRefs: 'مراجع حديث لا يمكن التحقق منها في مصادرنا',
  allVerified: 'إجابات كل نصوصها «مطابق للمصدر»',
  reportsTitle: 'التقارير في المستودع العام',
  judgesLink: 'للمحكّمين: تحقّق بنفسك',
  toolTitle: 'المقارنة بأداة عامة',
  toolIntro: 'الحالات الاثنتا عشرة نفسها في شات جي بي تي: أُرسلت في رسالة واحدة في محادثة محفوظة، وجاء الجواب كله في رد واحد، ونُسخ يدويًا بلا تعديل. جولة واحدة، والفحوص نفسها، وما لا يُحسم آليًا «يدوي» يحكم عليه الفريق من النص في التقرير.',
  toolModelUnknown: 'اسم النموذج لم يُسجَّل.',
  toolSetup: 'النموذج كما ظهر في التطبيق: ٦ أسترا، بدرجة تفكير «متوسط»، بحساب مدفوع؛ وظهر في الرد استعمال البحث في الويب.',
  sameModel: 'النموذج نفسه بلا مصادر',
  otherTool: 'شات جي بي تي',
}

const en: VerifyStrings = {
  title: 'Check it yourself',
  intro: "The official test cases from the challenge's scientific package, the app's answer to each, and the result of the live measurement.",
  demo: 'Sample data: these results come from a run in mock mode to try out the page, and will be replaced by the live measurement.',
  honest: 'Measured on {date} · Model: {model} · Manual cases are judged by the team.',
  modelMock: 'mock mode, no language model',
  packageArabic: "The package's texts are shown in Arabic, as written.",
  caseN: 'Case {n}',
  packageCase: 'Package case',
  question: 'The question asked',
  expected: "Expected behaviour (the package's words)",
  appDid: 'What the app did',
  type: { answer: 'Answer with the text and its reference', abstain: 'Apology: no matching text', referral: 'Referral to the fatwa authority', error: 'Run error' },
  disputed: 'Said that scholars hold more than one view',
  quotes: 'Sources shown',
  noQuotes: 'No sources',
  result: 'Result',
  pass: 'Pass',
  fail: 'Fail',
  manual: 'Manual',
  manualNote: 'Judged by the team: {text}',
  checks: 'Automatic checks',
  tryNow: 'Try it now',
  tryHint: 'Puts the question in the chat box; nothing is sent until you press send.',
  tally: '{pass} pass · {fail} fail · {manual} manual, of {n}',
  compareTitle: 'Against a general model',
  compareIntro: 'The same model answers with no passages and is asked to cite its source, on {n} test questions; the measurement is repeated three times.',
  compareNone: 'Not measured yet. This table is filled from the comparison report after the live measurement.',
  metric: 'Measure',
  run: 'Run {n}',
  general: 'General model',
  ours: 'Muslim',
  cites: 'Cites a reference',
  refsInSources: 'Quran references found in the sources',
  misattributed: 'Text attributed to a verse that does not match it',
  hadithRefs: 'Hadith references that cannot be checked in our sources',
  allVerified: 'Answers whose every text «matches the source»',
  reportsTitle: 'Reports on GitHub',
  judgesLink: 'For the judges: check it yourself',
  toolTitle: 'Against a general tool',
  toolIntro: 'The same twelve cases in ChatGPT: sent in one message in a saved chat, answered in one reply, and copied by hand without edit. One round, the same checks; what no rule can settle is «manual» and judged by the team from the text in the report.',
  toolModelUnknown: 'The model name was not recorded.',
  toolSetup: 'The model as shown in the app: 6 Astra, reasoning «medium», paid account; the reply showed that web search was used.',
  sameModel: 'The same model, no sources',
  otherTool: 'ChatGPT',
}

type Rest = Omit<VerifyStrings, 'type'> & { type: VerifyStrings['type'] }
const mt = (s: Partial<Rest>): VerifyStrings => ({ ...en, ...s, type: { ...en.type, ...s.type } })

export const VERIFY: Record<Lang, VerifyStrings> = {
  ar,
  en,
  ur: mt({
    title: 'خود جانچیں',
    intro: 'مقابلے کے سائنسی پیکج کے سرکاری آزمائشی کیس، ہر ایک پر ایپ کا جواب، اور براہِ راست پیمائش کا نتیجہ۔',
    demo: 'آزمائشی ڈیٹا: یہ نتائج صفحہ آزمانے کے لیے نقلی موڈ کی ایک دوڑ سے ہیں، اور براہِ راست پیمائش سے بدل دیے جائیں گے۔',
    honest: 'پیمائش کی تاریخ: {date} · ماڈل: {model} · دستی کیسوں کا فیصلہ ٹیم کرتی ہے۔',
    modelMock: 'نقلی موڈ، کوئی لسانی ماڈل نہیں',
    packageArabic: 'پیکج کی عبارتیں عربی میں جوں کی توں دکھائی گئی ہیں۔',
    caseN: 'کیس {n}',
    packageCase: 'پیکج کا کیس',
    question: 'پوچھا گیا سوال',
    expected: 'متوقع رویہ (پیکج کے الفاظ)',
    appDid: 'ایپ نے کیا کیا',
    type: { answer: 'متن اور حوالے کے ساتھ جواب', abstain: 'معذرت: کوئی مطابق متن نہیں', referral: 'فتویٰ کے ادارے کی طرف رہنمائی', error: 'چلانے میں خرابی' },
    disputed: 'بتایا کہ اس مسئلے میں ایک سے زیادہ اقوال ہیں',
    quotes: 'دکھائے گئے مآخذ',
    noQuotes: 'کوئی مآخذ نہیں',
    result: 'نتیجہ',
    pass: 'کامیاب',
    fail: 'ناکام',
    manual: 'دستی',
    manualNote: 'ٹیم فیصلہ کرتی ہے: {text}',
    checks: 'خودکار جانچ',
    tryNow: 'ابھی آزمائیں',
    tryHint: 'سوال گفتگو کے خانے میں رکھ دیتا ہے؛ آپ کے دبانے تک کچھ نہیں بھیجا جاتا۔',
    tally: '{n} میں سے {pass} کامیاب · {fail} ناکام · {manual} دستی',
    compareTitle: 'عام ماڈل سے موازنہ',
    compareIntro: 'وہی ماڈل بغیر اقتباسات کے جواب دیتا ہے اور اس سے ماخذ بتانے کو کہا جاتا ہے، {n} آزمائشی سوالوں پر؛ پیمائش تین بار دہرائی گئی۔',
    compareNone: 'ابھی پیمائش نہیں ہوئی۔ یہ جدول براہِ راست پیمائش کے بعد موازنے کی رپورٹ سے بھرا جائے گا۔',
    metric: 'پیمانہ',
    run: 'بار {n}',
    general: 'عام ماڈل',
    ours: 'مسلم',
    cites: 'حوالہ دیا',
    refsInSources: 'مآخذ میں موجود قرآنی حوالے',
    misattributed: 'کسی آیت سے منسوب ایسا متن جو اس سے مطابقت نہیں رکھتا',
    hadithRefs: 'حدیث کے حوالے جن کی ہمارے مآخذ میں جانچ ممکن نہیں',
    allVerified: 'جوابات جن کا ہر متن «ماخذ کے مطابق» ہے',
    reportsTitle: 'GitHub پر رپورٹیں',
    judgesLink: 'منصفین کے لیے: خود جانچیں',
    toolTitle: 'ایک عام ٹول سے موازنہ',
    toolIntro: 'یہی بارہ کیس ChatGPT میں: ایک محفوظ گفتگو میں ایک ہی پیغام میں بھیجے گئے، جواب ایک ہی جواب میں آیا، اور بغیر ترمیم ہاتھ سے نقل کیا گیا۔ ایک دور، وہی جانچ؛ جو کسی قاعدے سے طے نہ ہو وہ «دستی» ہے اور ٹیم رپورٹ کے متن سے فیصلہ کرتی ہے۔',
    toolModelUnknown: 'ماڈل کا نام درج نہیں ہوا۔',
    toolSetup: 'ایپ میں دکھایا گیا ماڈل: 6 Astra، سوچ کا درجہ «متوسط»، ادا شدہ اکاؤنٹ؛ جواب میں ویب تلاش کا استعمال ظاہر ہوا۔',
    sameModel: 'وہی ماڈل، بغیر ماخذ',
    otherTool: 'ChatGPT',
  }),
  id: mt({
    title: 'Periksa sendiri',
    intro: 'Kasus uji resmi dari paket ilmiah tantangan, jawaban aplikasi untuk tiap kasus, dan hasil pengukuran langsung.',
    demo: 'Data contoh: hasil ini berasal dari uji coba mode simulasi untuk mencoba halaman, dan akan diganti dengan pengukuran langsung.',
    honest: 'Tanggal pengukuran: {date} · Model: {model} · Kasus manual dinilai oleh tim.',
    modelMock: 'mode simulasi, tanpa model bahasa',
    packageArabic: 'Teks paket ditampilkan dalam bahasa Arab, apa adanya.',
    caseN: 'Kasus {n}',
    packageCase: 'Kasus paket',
    question: 'Pertanyaan yang diajukan',
    expected: 'Perilaku yang diharapkan (kata-kata paket)',
    appDid: 'Yang dilakukan aplikasi',
    type: { answer: 'Jawaban dengan teks dan rujukannya', abstain: 'Permohonan maaf: tidak ada teks yang cocok', referral: 'Rujukan ke lembaga fatwa', error: 'Galat saat dijalankan' },
    disputed: 'Menyatakan bahwa ulama memiliki lebih dari satu pendapat',
    quotes: 'Sumber yang ditampilkan',
    noQuotes: 'Tanpa sumber',
    result: 'Hasil',
    pass: 'Lulus',
    fail: 'Gagal',
    manual: 'Manual',
    manualNote: 'Dinilai oleh tim: {text}',
    checks: 'Pemeriksaan otomatis',
    tryNow: 'Coba sekarang',
    tryHint: 'Menaruh pertanyaan di kotak obrolan; tidak ada yang dikirim sampai Anda menekan kirim.',
    tally: '{pass} lulus · {fail} gagal · {manual} manual, dari {n}',
    compareTitle: 'Dibandingkan model umum',
    compareIntro: 'Model yang sama menjawab tanpa kutipan dan diminta menyebut sumbernya, pada {n} pertanyaan uji; pengukuran diulang tiga kali.',
    compareNone: 'Belum diukur. Tabel ini diisi dari laporan perbandingan setelah pengukuran langsung.',
    metric: 'Ukuran',
    run: 'Putaran {n}',
    general: 'Model umum',
    ours: 'Muslim',
    cites: 'Menyebut rujukan',
    refsInSources: 'Rujukan Al-Qur’an yang ada di sumber',
    misattributed: 'Teks yang dinisbatkan ke ayat tetapi tidak cocok',
    hadithRefs: 'Rujukan hadis yang tidak dapat diperiksa di sumber kami',
    allVerified: 'Jawaban yang semua teksnya «sesuai sumber»',
    reportsTitle: 'Laporan di GitHub',
    judgesLink: 'Untuk juri: periksa sendiri',
    toolTitle: 'Dibandingkan dengan alat umum',
    toolIntro: 'Dua belas kasus yang sama di ChatGPT: dikirim dalam satu pesan di obrolan tersimpan, dijawab dalam satu balasan, dan disalin manual tanpa diubah. Satu putaran, pemeriksaan yang sama; yang tidak bisa diputuskan aturan adalah «manual» dan dinilai tim dari teks di laporan.',
    toolModelUnknown: 'Nama modelnya tidak tercatat.',
    toolSetup: 'Model seperti tampil di aplikasi: 6 Astra, tingkat penalaran «sedang», akun berbayar; balasannya menunjukkan penggunaan pencarian web.',
    sameModel: 'Model yang sama, tanpa sumber',
    otherTool: 'ChatGPT',
  }),
  ms: mt({
    title: 'Semak sendiri',
    intro: 'Kes ujian rasmi daripada pakej ilmiah cabaran, jawapan aplikasi bagi setiap kes, dan hasil pengukuran langsung.',
    demo: 'Data contoh: keputusan ini daripada larian mod simulasi untuk mencuba halaman, dan akan diganti dengan pengukuran langsung.',
    honest: 'Tarikh pengukuran: {date} · Model: {model} · Kes manual dinilai oleh pasukan.',
    modelMock: 'mod simulasi, tanpa model bahasa',
    packageArabic: 'Teks pakej dipaparkan dalam bahasa Arab, seperti asal.',
    caseN: 'Kes {n}',
    packageCase: 'Kes pakej',
    question: 'Soalan yang ditanya',
    expected: 'Tingkah laku dijangka (kata-kata pakej)',
    appDid: 'Apa yang dilakukan aplikasi',
    type: { answer: 'Jawapan dengan teks dan rujukannya', abstain: 'Mohon maaf: tiada teks yang sepadan', referral: 'Rujukan kepada badan fatwa', error: 'Ralat semasa larian' },
    disputed: 'Menyatakan bahawa ulama mempunyai lebih daripada satu pendapat',
    quotes: 'Sumber dipaparkan',
    noQuotes: 'Tiada sumber',
    result: 'Keputusan',
    pass: 'Lulus',
    fail: 'Gagal',
    manual: 'Manual',
    manualNote: 'Dinilai oleh pasukan: {text}',
    checks: 'Semakan automatik',
    tryNow: 'Cuba sekarang',
    tryHint: 'Meletakkan soalan dalam kotak sembang; tiada apa dihantar sehingga anda menekan hantar.',
    tally: '{pass} lulus · {fail} gagal · {manual} manual, daripada {n}',
    compareTitle: 'Berbanding model umum',
    compareIntro: 'Model yang sama menjawab tanpa petikan dan diminta menyebut sumbernya, pada {n} soalan ujian; pengukuran diulang tiga kali.',
    compareNone: 'Belum diukur. Jadual ini diisi daripada laporan perbandingan selepas pengukuran langsung.',
    metric: 'Ukuran',
    run: 'Larian {n}',
    general: 'Model umum',
    ours: 'Muslim',
    cites: 'Menyebut rujukan',
    refsInSources: 'Rujukan al-Quran yang ada dalam sumber',
    misattributed: 'Teks yang dinisbahkan kepada ayat tetapi tidak sepadan',
    hadithRefs: 'Rujukan hadis yang tidak dapat disemak dalam sumber kami',
    allVerified: 'Jawapan yang semua teksnya «sepadan dengan sumber»',
    reportsTitle: 'Laporan di GitHub',
    judgesLink: 'Untuk hakim: semak sendiri',
    toolTitle: 'Berbanding alat umum',
    toolIntro: 'Dua belas kes yang sama dalam ChatGPT: dihantar dalam satu mesej dalam sembang yang disimpan, dijawab dalam satu balasan, dan disalin secara manual tanpa suntingan. Satu pusingan, semakan yang sama; yang tidak dapat diputuskan peraturan ialah «manual» dan dinilai pasukan daripada teks dalam laporan.',
    toolModelUnknown: 'Nama model tidak direkodkan.',
    toolSetup: 'Model seperti dipaparkan dalam aplikasi: 6 Astra, tahap penaakulan «sederhana», akaun berbayar; balasan menunjukkan carian web digunakan.',
    sameModel: 'Model yang sama, tanpa sumber',
    otherTool: 'ChatGPT',
  }),
  tr: mt({
    title: 'Kendiniz doğrulayın',
    intro: 'Yarışmanın bilimsel paketindeki resmî test vakaları, uygulamanın her birine cevabı ve canlı ölçümün sonucu.',
    demo: 'Örnek veri: bu sonuçlar sayfayı denemek için simülasyon modunda yapılan bir çalıştırmadan gelir ve canlı ölçümle değiştirilecektir.',
    honest: 'Ölçüm tarihi: {date} · Model: {model} · Elle değerlendirilen vakalara ekip karar verir.',
    modelMock: 'simülasyon modu, dil modeli yok',
    packageArabic: 'Paketin metinleri Arapça, olduğu gibi gösterilir.',
    caseN: 'Vaka {n}',
    packageCase: 'Paket vakası',
    question: 'Sorulan soru',
    expected: 'Beklenen davranış (paketin ifadesi)',
    appDid: 'Uygulamanın yaptığı',
    type: { answer: 'Metni ve kaynağıyla cevap', abstain: 'Özür: eşleşen metin yok', referral: 'Fetva merciine yönlendirme', error: 'Çalıştırma hatası' },
    disputed: 'Âlimlerin birden fazla görüşü olduğunu belirtti',
    quotes: 'Gösterilen kaynaklar',
    noQuotes: 'Kaynak yok',
    result: 'Sonuç',
    pass: 'Başarılı',
    fail: 'Başarısız',
    manual: 'Elle',
    manualNote: 'Ekip karar verir: {text}',
    checks: 'Otomatik kontroller',
    tryNow: 'Şimdi deneyin',
    tryHint: 'Soruyu sohbet kutusuna koyar; siz gönder düğmesine basana kadar hiçbir şey gönderilmez.',
    tally: '{n} vakadan {pass} başarılı · {fail} başarısız · {manual} elle',
    compareTitle: 'Genel bir modelle karşılaştırma',
    compareIntro: 'Aynı model alıntı olmadan cevap verir ve kaynağını belirtmesi istenir; {n} test sorusunda, ölçüm üç kez tekrarlandı.',
    compareNone: 'Henüz ölçülmedi. Bu tablo canlı ölçümden sonra karşılaştırma raporundan doldurulur.',
    metric: 'Ölçüt',
    run: '{n}. çalıştırma',
    general: 'Genel model',
    ours: 'Muslim',
    cites: 'Kaynak belirtti',
    refsInSources: 'Kaynaklarda bulunan Kur’an atıfları',
    misattributed: 'Bir ayete nispet edilip onunla uyuşmayan metin',
    hadithRefs: 'Kaynaklarımızda doğrulanamayan hadis atıfları',
    allVerified: 'Bütün metinleri «kaynakla aynı» olan cevaplar',
    reportsTitle: 'GitHub’daki raporlar',
    judgesLink: 'Jüri için: kendiniz doğrulayın',
    toolTitle: 'Genel bir araçla karşılaştırma',
    toolIntro: 'Aynı on iki vaka ChatGPT\'de: kayıtlı bir sohbette tek mesajda gönderildi, tek yanıtta cevaplandı ve elle, değiştirilmeden kopyalandı. Tek tur, aynı kontroller; hiçbir kuralın karara bağlayamadığı «elle» olarak işaretlenir ve ekip rapordaki metinden karar verir.',
    toolModelUnknown: 'Model adı kaydedilmedi.',
    toolSetup: 'Uygulamada görünen model: 6 Astra, düşünme düzeyi «orta», ücretli hesap; yanıtta web araması kullanıldığı görüldü.',
    sameModel: 'Aynı model, kaynaksız',
    otherTool: 'ChatGPT',
  }),
  fr: mt({
    title: 'Vérifiez par vous-même',
    intro: 'Les cas de test officiels du dossier scientifique du concours, la réponse de l’application à chacun et le résultat de la mesure en direct.',
    demo: 'Données d’exemple : ces résultats viennent d’un passage en mode simulation pour essayer la page, et seront remplacés par la mesure en direct.',
    honest: 'Mesuré le {date} · Modèle : {model} · Les cas manuels sont jugés par l’équipe.',
    modelMock: 'mode simulation, sans modèle de langue',
    packageArabic: 'Les textes du dossier sont affichés en arabe, tels quels.',
    caseN: 'Cas {n}',
    packageCase: 'Cas du dossier',
    question: 'La question posée',
    expected: 'Comportement attendu (termes du dossier)',
    appDid: 'Ce qu’a fait l’application',
    type: { answer: 'Réponse avec le texte et sa référence', abstain: 'Excuse : aucun texte correspondant', referral: 'Renvoi à l’instance de fatwa', error: 'Erreur d’exécution' },
    disputed: 'A indiqué que les savants ont plus d’un avis',
    quotes: 'Sources affichées',
    noQuotes: 'Aucune source',
    result: 'Résultat',
    pass: 'Réussi',
    fail: 'Échoué',
    manual: 'Manuel',
    manualNote: 'Jugé par l’équipe : {text}',
    checks: 'Vérifications automatiques',
    tryNow: 'Essayer maintenant',
    tryHint: 'Place la question dans la zone de discussion ; rien n’est envoyé avant que vous appuyiez sur envoyer.',
    tally: 'Réussis : {pass} · échoués : {fail} · manuels : {manual}, sur {n}',
    compareTitle: 'Face à un modèle généraliste',
    compareIntro: 'Le même modèle répond sans passages et doit citer sa source, sur {n} questions de test ; la mesure est répétée trois fois.',
    compareNone: 'Pas encore mesuré. Ce tableau sera rempli à partir du rapport de comparaison après la mesure en direct.',
    metric: 'Mesure',
    run: 'Passage {n}',
    general: 'Modèle généraliste',
    ours: 'Muslim',
    cites: 'Cite une référence',
    refsInSources: 'Références coraniques présentes dans les sources',
    misattributed: 'Texte attribué à un verset sans lui correspondre',
    hadithRefs: 'Références de hadith invérifiables dans nos sources',
    allVerified: 'Réponses dont tous les textes « correspondent à la source »',
    reportsTitle: 'Rapports sur GitHub',
    judgesLink: 'Pour le jury : vérifiez par vous-même',
    toolTitle: 'Face à un outil généraliste',
    toolIntro: 'Les mêmes douze cas dans ChatGPT : envoyés en un seul message dans une discussion enregistrée, une seule réponse, copiée à la main sans retouche. Un seul tour, les mêmes vérifications ; ce qu’aucune règle ne tranche est « manuel » et jugé par l’équipe sur le texte du rapport.',
    toolModelUnknown: 'Le nom du modèle n’a pas été noté.',
    toolSetup: 'Le modèle tel qu’affiché dans l’application : 6 Astra, niveau de réflexion « moyen », compte payant ; la réponse montrait une recherche sur le web.',
    sameModel: 'Le même modèle, sans sources',
    otherTool: 'ChatGPT',
  }),
  es: mt({
    title: 'Compruébelo usted',
    intro: 'Los casos de prueba oficiales del paquete científico del concurso, la respuesta de la aplicación a cada uno y el resultado de la medición en vivo.',
    demo: 'Datos de ejemplo: estos resultados provienen de una ejecución en modo simulación para probar la página, y se sustituirán por la medición en vivo.',
    honest: 'Fecha de medición: {date} · Modelo: {model} · Los casos manuales los juzga el equipo.',
    modelMock: 'modo simulación, sin modelo de lenguaje',
    packageArabic: 'Los textos del paquete se muestran en árabe, tal cual.',
    caseN: 'Caso {n}',
    packageCase: 'Caso del paquete',
    question: 'La pregunta formulada',
    expected: 'Comportamiento esperado (palabras del paquete)',
    appDid: 'Lo que hizo la aplicación',
    type: { answer: 'Respuesta con el texto y su referencia', abstain: 'Disculpa: ningún texto coincide', referral: 'Remisión a la autoridad de fatwa', error: 'Error de ejecución' },
    disputed: 'Indicó que los sabios tienen más de una opinión',
    quotes: 'Fuentes mostradas',
    noQuotes: 'Sin fuentes',
    result: 'Resultado',
    pass: 'Aprobado',
    fail: 'Suspendido',
    manual: 'Manual',
    manualNote: 'Lo juzga el equipo: {text}',
    checks: 'Comprobaciones automáticas',
    tryNow: 'Probar ahora',
    tryHint: 'Pone la pregunta en el cuadro de chat; no se envía nada hasta que usted pulse enviar.',
    tally: 'Aprobados: {pass} · suspendidos: {fail} · manuales: {manual}, de {n}',
    compareTitle: 'Frente a un modelo general',
    compareIntro: 'El mismo modelo responde sin pasajes y se le pide citar su fuente, en {n} preguntas de prueba; la medición se repite tres veces.',
    compareNone: 'Aún no medido. Esta tabla se llena con el informe de comparación tras la medición en vivo.',
    metric: 'Medida',
    run: 'Ejecución {n}',
    general: 'Modelo general',
    ours: 'Muslim',
    cites: 'Cita una referencia',
    refsInSources: 'Referencias coránicas presentes en las fuentes',
    misattributed: 'Texto atribuido a una aleya que no coincide con ella',
    hadithRefs: 'Referencias de hadiz que no se pueden comprobar en nuestras fuentes',
    allVerified: 'Respuestas con todos sus textos «iguales a la fuente»',
    reportsTitle: 'Informes en GitHub',
    judgesLink: 'Para el jurado: compruébelo usted',
    toolTitle: 'Frente a una herramienta general',
    toolIntro: 'Los mismos doce casos en ChatGPT: enviados en un solo mensaje en un chat guardado, respondidos en una sola respuesta y copiados a mano sin cambios. Una sola ronda, las mismas comprobaciones; lo que ninguna regla resuelve es «manual» y lo juzga el equipo a partir del texto del informe.',
    toolModelUnknown: 'No se anotó el nombre del modelo.',
    toolSetup: 'El modelo tal como apareció en la aplicación: 6 Astra, nivel de razonamiento «medio», cuenta de pago; la respuesta mostró uso de búsqueda web.',
    sameModel: 'El mismo modelo, sin fuentes',
    otherTool: 'ChatGPT',
  }),
  bn: mt({
    title: 'নিজে যাচাই করুন',
    intro: 'প্রতিযোগিতার বৈজ্ঞানিক প্যাকেজের দাপ্তরিক পরীক্ষার কেস, প্রতিটির ওপর অ্যাপের উত্তর, এবং সরাসরি পরিমাপের ফল।',
    demo: 'নমুনা তথ্য: এই ফলাফল পাতাটি পরখ করতে সিমুলেশন মোডের একটি রান থেকে, এবং সরাসরি পরিমাপ দিয়ে বদলানো হবে।',
    honest: 'পরিমাপের তারিখ: {date} · মডেল: {model} · হাতে-বিচারের কেসগুলোর রায় দল দেয়।',
    modelMock: 'সিমুলেশন মোড, কোনো ভাষা মডেল নেই',
    packageArabic: 'প্যাকেজের লেখা আরবিতে, যেমন আছে তেমন দেখানো হয়েছে।',
    caseN: 'কেস {n}',
    packageCase: 'প্যাকেজের কেস',
    question: 'যে প্রশ্ন করা হয়েছে',
    expected: 'প্রত্যাশিত আচরণ (প্যাকেজের ভাষায়)',
    appDid: 'অ্যাপ যা করেছে',
    type: { answer: 'লেখা ও সূত্রসহ উত্তর', abstain: 'দুঃখপ্রকাশ: মিলে যায় এমন লেখা নেই', referral: 'ফতোয়া কর্তৃপক্ষের কাছে পাঠানো', error: 'চালাতে ত্রুটি' },
    disputed: 'জানিয়েছে যে আলেমদের একাধিক মত আছে',
    quotes: 'দেখানো সূত্র',
    noQuotes: 'কোনো সূত্র নেই',
    result: 'ফল',
    pass: 'উত্তীর্ণ',
    fail: 'অনুত্তীর্ণ',
    manual: 'হাতে-বিচার',
    manualNote: 'দল রায় দেয়: {text}',
    checks: 'স্বয়ংক্রিয় পরীক্ষা',
    tryNow: 'এখন চেষ্টা করুন',
    tryHint: 'প্রশ্নটি চ্যাটের ঘরে রাখে; আপনি পাঠান চাপার আগে কিছুই পাঠানো হয় না।',
    tally: '{n}টির মধ্যে {pass} উত্তীর্ণ · {fail} অনুত্তীর্ণ · {manual} হাতে-বিচার',
    compareTitle: 'সাধারণ মডেলের সাথে তুলনা',
    compareIntro: 'একই মডেল কোনো উদ্ধৃতি ছাড়া উত্তর দেয় এবং তাকে সূত্র বলতে বলা হয়, {n}টি পরীক্ষার প্রশ্নে; পরিমাপ তিনবার করা হয়েছে।',
    compareNone: 'এখনো পরিমাপ হয়নি। সরাসরি পরিমাপের পর তুলনার প্রতিবেদন থেকে এই সারণি পূরণ হবে।',
    metric: 'মাপকাঠি',
    run: 'রান {n}',
    general: 'সাধারণ মডেল',
    ours: 'মুসলিম',
    cites: 'সূত্র উল্লেখ করেছে',
    refsInSources: 'সূত্রে থাকা কুরআনের উদ্ধৃতি',
    misattributed: 'কোনো আয়াতের নামে এমন লেখা যা তার সাথে মেলে না',
    hadithRefs: 'হাদিসের সূত্র যা আমাদের উৎসে যাচাই করা যায় না',
    allVerified: 'যে উত্তরগুলোর সব লেখা «উৎসের সাথে মিলে»',
    reportsTitle: 'GitHub-এ প্রতিবেদন',
    judgesLink: 'বিচারকদের জন্য: নিজে যাচাই করুন',
    toolTitle: 'একটি সাধারণ টুলের সঙ্গে তুলনা',
    toolIntro: 'একই বারোটি কেস ChatGPT-তে: একটি সংরক্ষিত চ্যাটে এক বার্তায় পাঠানো হয়েছে, এক উত্তরে জবাব এসেছে, এবং কোনো পরিবর্তন ছাড়া হাতে কপি করা হয়েছে। এক দফা, একই যাচাই; কোনো নিয়মে যা নিষ্পত্তি হয় না তা «ম্যানুয়াল», এবং দল প্রতিবেদনের লেখা দেখে বিচার করে।',
    toolModelUnknown: 'মডেলের নাম লেখা হয়নি।',
    toolSetup: 'অ্যাপে দেখানো মডেল: 6 Astra, চিন্তার স্তর «মাঝারি», পেইড অ্যাকাউন্ট; উত্তরে ওয়েব অনুসন্ধানের ব্যবহার দেখা গেছে।',
    sameModel: 'একই মডেল, উৎস ছাড়া',
    otherTool: 'ChatGPT',
  }),
  hi: mt({
    title: 'ख़ुद जाँचें',
    intro: 'प्रतियोगिता के वैज्ञानिक पैकेज के आधिकारिक परीक्षण मामले, हर एक पर ऐप का उत्तर, और लाइव माप का परिणाम।',
    demo: 'नमूना डेटा: ये परिणाम पेज आज़माने के लिए सिमुलेशन मोड की एक रन से हैं, और लाइव माप से बदल दिए जाएँगे।',
    honest: 'माप की तारीख़: {date} · मॉडल: {model} · हाथ से जाँचे जाने वाले मामलों का निर्णय टीम करती है।',
    modelMock: 'सिमुलेशन मोड, कोई भाषा मॉडल नहीं',
    packageArabic: 'पैकेज के पाठ अरबी में, ज्यों के त्यों दिखाए गए हैं।',
    caseN: 'मामला {n}',
    packageCase: 'पैकेज का मामला',
    question: 'पूछा गया प्रश्न',
    expected: 'अपेक्षित व्यवहार (पैकेज के शब्द)',
    appDid: 'ऐप ने क्या किया',
    type: { answer: 'पाठ और उसके संदर्भ के साथ उत्तर', abstain: 'क्षमा: कोई मेल खाता पाठ नहीं', referral: 'फ़तवा संस्था की ओर भेजना', error: 'चलाने में त्रुटि' },
    disputed: 'बताया कि विद्वानों के एक से अधिक मत हैं',
    quotes: 'दिखाए गए स्रोत',
    noQuotes: 'कोई स्रोत नहीं',
    result: 'परिणाम',
    pass: 'सफल',
    fail: 'असफल',
    manual: 'हाथ से',
    manualNote: 'टीम निर्णय करती है: {text}',
    checks: 'स्वचालित जाँच',
    tryNow: 'अभी आज़माएँ',
    tryHint: 'प्रश्न को चैट बॉक्स में रख देता है; आपके भेजें दबाने तक कुछ नहीं भेजा जाता।',
    tally: '{n} में से {pass} सफल · {fail} असफल · {manual} हाथ से',
    compareTitle: 'सामान्य मॉडल से तुलना',
    compareIntro: 'वही मॉडल बिना अंशों के उत्तर देता है और उससे स्रोत बताने को कहा जाता है, {n} परीक्षण प्रश्नों पर; माप तीन बार दोहराया गया।',
    compareNone: 'अभी मापा नहीं गया। लाइव माप के बाद तुलना रिपोर्ट से यह तालिका भरी जाएगी।',
    metric: 'माप',
    run: 'रन {n}',
    general: 'सामान्य मॉडल',
    ours: 'मुस्लिम',
    cites: 'संदर्भ बताया',
    refsInSources: 'स्रोतों में मौजूद क़ुरआन संदर्भ',
    misattributed: 'किसी आयत से जोड़ा गया पाठ जो उससे मेल नहीं खाता',
    hadithRefs: 'हदीस संदर्भ जिनकी हमारे स्रोतों में जाँच संभव नहीं',
    allVerified: 'उत्तर जिनका हर पाठ «स्रोत से मेल खाता» है',
    reportsTitle: 'GitHub पर रिपोर्टें',
    judgesLink: 'निर्णायकों के लिए: ख़ुद जाँचें',
    toolTitle: 'एक सामान्य टूल से तुलना',
    toolIntro: 'वही बारह केस ChatGPT में: एक सहेजी गई चैट में एक ही संदेश में भेजे गए, एक ही जवाब में उत्तर आया, और बिना बदलाव हाथ से कॉपी किया गया। एक दौर, वही जाँचें; जो किसी नियम से तय न हो वह «मैनुअल» है और टीम रिपोर्ट के पाठ से तय करती है।',
    toolModelUnknown: 'मॉडल का नाम दर्ज नहीं हुआ।',
    toolSetup: 'ऐप में दिखाया गया मॉडल: 6 Astra, सोचने का स्तर «मध्यम», भुगतान वाला खाता; जवाब में वेब खोज का इस्तेमाल दिखा।',
    sameModel: 'वही मॉडल, बिना स्रोत',
    otherTool: 'ChatGPT',
  }),
}
