// Voice conversation (command 12) never reads the text of an ayah. Inside the app only the ayat of a reply are known,
// so this script finds, once, from data/processed, the Quran text that the app could not recognise by itself:
//   passages: in each creed passage, outside its marked quotations ({…}, "…", «…»), any phrase of 6+ consecutive
//             words that is in some ayah (an unmarked quotation, e.g. Ibn al-Qayyim citing Sad 38:27 in
//             Kitab al-Tawhid), stored folded; the app replaces it like a marked ayah.
//   muyassarQuotesOtherAyat: ayat whose al-Tafsir al-Muyassar contains 6+ words of another ayah; it is not read.
// Output: web/src/config/voice-guard.json (short phrases and ids only, no full texts). Run again after any re-ingest:
//   node scripts/ingest/voice-guard.mjs
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { matchWords, splitPassage } from '../../web/src/trust/sacred.ts'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const read = (f) => fs.readFileSync(path.join(ROOT, 'data/processed', f), 'utf8').trim().split('\n').map((l) => JSON.parse(l))
const quran = read('quran.jsonl')
const aqeedah = read('aqeedah.jsonl')
const N = 6

const grams = new Map()
for (const r of quran) {
  const w = matchWords(r.text)
  for (let i = 0; i + N <= w.length; i++) {
    const g = w.slice(i, i + N).join(' ')
    if (!grams.has(g)) grams.set(g, r.id)
  }
}

/** Maximal spans of words covered by 6-word runs found in the Quran (other than `self`), folded. */
function quranSpans(text, self) {
  const w = matchWords(text)
  const covered = new Array(w.length).fill(false)
  const ids = new Set()
  for (let i = 0; i + N <= w.length; i++) {
    const id = grams.get(w.slice(i, i + N).join(' '))
    if (id && id !== self) {
      ids.add(id)
      for (let k = i; k < i + N; k++) covered[k] = true
    }
  }
  const spans = []
  for (let i = 0; i < w.length; i++) {
    if (!covered[i]) continue
    let j = i
    while (j < w.length && covered[j]) j++
    spans.push(w.slice(i, j).join(' '))
    i = j
  }
  return { spans, ids: [...ids] }
}

const passages = {}
const found = []
for (const r of aqeedah) {
  const { parts, paired } = splitPassage(r.text)
  if (!paired) continue // not read aloud at all
  const plain = parts.filter((p) => p.kind === 'plain').map((p) => p.text).join(' \n ')
  const { spans, ids } = quranSpans(plain)
  if (spans.length) {
    passages[r.id] = spans
    found.push(`${r.id}: ${ids.join(', ')}`)
  }
}

const muyassarQuotesOtherAyat = quran.filter((r) => r.muyassar && quranSpans(r.muyassar, r.id).spans.length).map((r) => r.id)

const out = {
  about: 'Generated by scripts/ingest/voice-guard.mjs from data/processed; read by web/src/trust/speakable.ts. Do not edit by hand.',
  generated: new Date().toISOString().slice(0, 10),
  wordsInARow: N,
  passages,
  muyassarQuotesOtherAyat,
}
fs.writeFileSync(path.join(ROOT, 'web/src/config/voice-guard.json'), JSON.stringify(out, null, 1) + '\n')
console.log(`passages with unmarked Quran text: ${found.length}`)
for (const f of found) console.log(`  ${f}`)
console.log(`ayat whose al-Muyassar quotes another ayah: ${muyassarQuotesOtherAyat.length}`)
